name: Deploy to ECR

on:
  push:
    branches: [dev]

permissions:
  id-token: write # here
  contents: read
  security-events: write # 보안 리포트
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: qwik-api-repo-dev
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      # 정적분석
      - name: Semgrep Static Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          auditOn: push

      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::294327208573:role/oidc-role # here
          aws-region: ap-northeast-2

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # 의존성 분석
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: "table"
          exit-code: "1" # CRITICAL/HIGH 발견 시 파이프라인 중단
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
